services:
  nginx:
    build: ./nginx
    image: nginx
    restart: unless-stopped
    container_name: "nginx_cont"
  
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf/dhparam.pem:/etc/ssl/certs/dhparam.pem 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot  
      - ./staticfiles:/var/www/edugenius.tech/staticfiles
      - ./media:/media/

  db:
    container_name: school-db-container
    image: mysql:8
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    volumes:
      - ./mysql_data:/var/lib/mysql/

  backend:
    image: school-image
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "gunicorn --timeout 500 school_managment_saas.wsgi --workers 3 --bind 0.0.0.0:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=mysql://${SQL_USER}:${SQL_PASSWORD}@db:3306/${SQL_DATABASE}
    volumes:
      - .:/school_managment_saas
      - ./mysql_data:/var/lib/mysql/
      - ./staticfiles:/var/www/edugenius.tech/staticfiles
      - ./media:/media
      - ./logs:/school_managment_saas/logs

    depends_on:
      - db
    links:
      - db

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email eedugenius@gmail.com -d edugenius.tech --agree-tos
