services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx_cont"
    ports:
      - 80:80 
    depends_on:
      - django_project
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Mount nginx configuration
      - ./static_files:/school_managment_saas/static_files  # Serve static files from the host to nginx container
      - ./media:/media  
  db:
    container_name: school-db-container
    image: mysql:8
    restart: always
    ports:
      - "3308:3306"
    env_file:
      - ./.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=0
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=${SQL_ROOT_PASSWORD}
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DATABASE}
    volumes:
      - /tmp/school_managment_saas/mysqld:/var/lib/mysqld/
      - ./my.cnf:/etc/mysql/my.cnf
       
    
  django_project:
      image: school-image
      
      build: 
        context: .
        dockerfile: Dockerfile
      command: "gunicorn school_managment_saas.wsgi --workers 3 --bind 0.0.0.0:8001"

      env_file:
        - .env
      environment:
        - DATABASE_URL=mysql://${SQL_USER}:${SQL_PASSWORD}@db:3306/${SQL_DATABASE}
      ports:
        - "8000:8000"
      volumes:
        - .:/school_managment_saas
        - /tmp/school_managment_saas/mysqld:/var/lib/mysqld/
        - ./static_files:/school_managment_saas/static_files/
        - ./media:/media 
      depends_on:
        - db
      links:
        - db

volumes:
    db:
      name: school-docker-env
      driver: local  