"""
Django settings for school_managment_saas project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from django.core.management.utils import get_random_secret_key
from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

import firebase_admin
from firebase_admin import credentials


 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_PATH = os.path.realpath(os.path.dirname(__file__))
 

SIGNING_KEY = os.environ.get("SIGNING_KEY")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY","qdqsffoizjhiouefnziufoehfouzbfi6541fzelkjnoi")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ["seashell-app-ew5be.ondigitalocean.app"]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://edugenius",
    "http://localhost",
    "http://localhost",
    "https://seashell-app-ew5be.ondigitalocean.app"
]




CSRF_TRUSTED_ORIGINS = [
    'http://localhost',
    'http://127.0.0.1',
    'http://edugenius'   ,
    "https://seashell-app-ew5be.ondigitalocean.app"
]

# EMAIL CONFIG
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_HOST_USER = "dananeabdjalil2@gmail.com"
EMAIL_HOST_PASSWORD = "iubd hmzq zjri fnbr "
EMAIL_USE_TLS = True


cred = credentials.Certificate("school_managment_saas/edugenius-5b7b0-firebase-adminsdk-9dlmq-444eb0a1f3.json")
firebase_admin.initialize_app(cred)

FCM_DJANGO_SETTINGS = {
    # default: _('FCM Django')
    # "APP_VERBOSE_NAME": "[string for AppConfig's verbose_name]",
    # true if you want to have only one active device per registered user at a time
    # default: False
    "ONE_DEVICE_PER_USER": False,
    # devices to which notifications cannot be sent,
    # are deleted upon receiving error response from FCM
    # default: False
    "DELETE_INACTIVE_DEVICES": False,
}
INSTALLED_APPS = [
    "unfold",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "rest_framework_simplejwt",
    "phonenumber_field",
    "school_managment",
    "channels",
    "djoser",
     
    "htmx",
    "corsheaders",
    "fcm_django",
    "drf_yasg",
]

MIDDLEWARE = [
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
]

CORS_ALLOW_METHODS = (
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
)

ROOT_URLCONF = "school_managment_saas.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "school_managment_saas.wsgi.application"
ASGI_APPLICATION = "school_managment_saas.asgi.application"

CHANNEL_LAYERS = {"default": {"BACKEND": "channels.layers.InMemoryChannelLayer"}}

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE":os.environ.get("SQL_ENGINE",  "django.db.backends.mysql"),
        "NAME":  os.environ.get("SQL_DATABASE",'school_managment_db' ),
        "HOST": os.environ.get("SQL_HOST",'db' ),
        "PORT": os.environ.get("SQL_PORT", "3306"),
        "USER": os.environ.get("SQL_USER",'root'),
        "PASSWORD": os.environ.get("SQL_PASSWORD",'mythologie'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
PHONENUMBER_DB_FORMAT = "NATIONAL"
PHONENUMBER_DEFAULT_REGION = "MA"

STATIC_ROOT = os.path.join(BASE_DIR, 'static_files')
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
 

STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "media")
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


TIME_INPUT_FORMATS = [
    # '2006-10-25'
    "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
    "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
    "%m/%d/%Y",  # '10/25/2006'
    "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
    "%m/%d/%y %H:%M",  # '10/25/06 14:30'
    "%m/%d/%y",
    "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
    "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
    "%Y-%m-%d",
]  # '10/25/06'


AUTH_USER_MODEL = "school_managment.Person"
AUTHENTICATION_BACKENDS = [
    "school_managment.authentication.PersonAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",  # Default backend
]

REST_FRAMEWORK = {
    
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle",
    ],
    "DEFAULT_THROTTLE_RATES": {"anon": "30/min", "user": "60/min"},
    "DATE_INPUT_FORMATS": [
        # '2006-10-25'
        "%m/%d/%Y %H:%M:%S",  # '10/25/2006 14:30:59'
        "%m/%d/%Y %H:%M",  # '10/25/2006 14:30'
        "%m/%d/%Y",  # '10/25/2006'
        "%m/%d/%y %H:%M:%S",  # '10/25/06 14:30:59'
        "%m/%d/%y %H:%M",  # '10/25/06 14:30'
        "%m/%d/%y",
        "%Y-%m-%d %H:%M:%S",  # '2006-10-25 14:30:59'
        "%Y-%m-%d %H:%M",  # '2006-10-25 14:30'
        "%Y-%m-%d",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 2,
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=300),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=300),
    "USER_ID_FIELD": "email",  # or any other unique field for your user model
    "ALGORITHM": "HS256",
    # Change this to a strong, unique secret key
    "SIGNING_KEY": SIGNING_KEY,
    "AUTH_HEADER_TYPES": ("JWT",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
}
DOMAIN = "localhost:8000"
DJOSER = {
    "USER_ID_FIELD": "email",
    "PASSWORD_RESET_CONFIRM_URL": "auth/reset-password/{uid}/{token}",
    "USERNAME_RESET_CONFIRM_URL": "username/reset/confirm/?uid={email}&token={token}",
    "ACTIVATION_URL": "auth/activate/?uid={uid}&token={token}",
    "SEND_ACTIVATION_EMAIL": True,
    "SEND_CONFIRMATION_EMAIL": True,
    "PASSWORD_CHANGED_EMAIL_CONFIRMATION": True,
    "SET_PASSWORD_RETYPE": True,
    "PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND": True,
    "SERIALIZERS": {
        "user_create": "school_managment.serialization.PersonSerializer",
        "user": "school_managment.serialization.PersonSerializer",
        "current_user": "school_managment.serialization.PersonSerializer",
        "password_reset_confirm": "school_managment.serialization.CustomPasswordResetConfirmSerializer",
        "token_create": "school_managment.serialization.CustomTokenObtainPairSerializer",
    },
}
