# renew_before_expiry = 30 days
version = 3.0.1
archive_dir = /etc/letsencrypt/archive/edugenius.tech
cert = /etc/letsencrypt/live/edugenius.tech/cert.pem
privkey = /etc/letsencrypt/live/edugenius.tech/privkey.pem
chain = /etc/letsencrypt/live/edugenius.tech/chain.pem
fullchain = /etc/letsencrypt/live/edugenius.tech/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = ca69cdbeb74d8066ec5e12ac11d2b4a6
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
www.edugenius.tech = /var/www/certbot
