# Generated by Django 5.0.1 on 2024-02-07 14:53

import django.db.models.deletion
import django_mysql.models
import school_managment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to=school_managment.models.upload_to)),
                ('education_stage', django_mysql.models.ListCharField(models.CharField(choices=[('EL', 'ELMENTARY'), ('PR', 'PRIMARY'), ('LY', 'LYCEE'), ('UN', 'UNIVERSITY')], default='PR', max_length=2), default='PR', max_length=12, size=4)),
            ],
            options={
                'verbose_name': 'School Data',
                'verbose_name_plural': 'School Data',
                'db_table': 'school_data_tb',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=school_managment.models.upload_to)),
                ('gender', models.CharField(choices=[('M', 'MEN'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='person_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='person_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('classes_taught', models.ManyToManyField(blank=True, related_name='classrooms_taught', to='school_managment.class')),
            ],
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('exam_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('class_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel'),
        ),
        migrations.CreateModel(
            name='SchoolMembers',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OW', 'OWNER'), ('SF', 'STAFF'), ('TE', 'TEACHER'), ('ST', 'STUDENT')], default='SF', max_length=2)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
            options={
                'verbose_name': 'SchoolMember',
                'verbose_name_plural': 'SchoolMembers',
                'db_table': 'SchoolMembers',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('exam', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.student')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('parent_id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.student')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=255)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.student')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_association',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.subject'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects_taught',
            field=models.ManyToManyField(blank=True, related_name='classrooms_taught', to='school_managment.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('teaching_classes', models.ManyToManyField(blank=True, related_name='teachers', to='school_managment.class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school_managment.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('class_name', 'school')},
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.student')),
            ],
            options={
                'unique_together': {('date', 'student')},
            },
        ),
    ]
