# Generated by Django 5.0.1 on 2024-09-26 00:24

import django.db.models.deletion
import django_mysql.models
import phonenumber_field.modelfields
import school_managment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('gender', models.CharField(choices=[('M', 'MEN'), ('F', 'FEMALE')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_owner', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('birth_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=200)),
                ('grade', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'db_table': 'Classe',
            },
        ),
        migrations.CreateModel(
            name='SchoolDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to=school_managment.models.upload_to)),
                ('education_stage', django_mysql.models.ListCharField(models.CharField(choices=[('EL', 'ELMENTARY'), ('PR', 'PRIMARY'), ('LY', 'LYCEE'), ('UN', 'UNIVERSITY')], default='PR', max_length=2), default='PR', max_length=12, size=4)),
            ],
            options={
                'verbose_name': 'School Data',
                'verbose_name_plural': 'School Data',
                'db_table': 'school_data_tb',
            },
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=255, null=True)),
                ('is_virtual', models.BooleanField(default=False)),
                ('classes_taught', models.ManyToManyField(blank=True, related_name='classrooms_taught', to='school_managment.classe')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
            options={
                'verbose_name': 'Classe Room',
                'verbose_name_plural': 'Classe Rooms',
                'db_table': 'ClassRoom',
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.classroom')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
            options={
                'verbose_name': 'Classe Schedule',
                'verbose_name_plural': 'Classe Schedules',
                'db_table': 'ClassSchedule',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('desricption', models.TextField(blank=True, default='no description', max_length=300)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('color', models.CharField(max_length=12)),
                ('is_all_day', models.BooleanField(default=False)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='classe',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel'),
        ),
        migrations.CreateModel(
            name='SchoolMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=school_managment.models.upload_to)),
                ('role', models.CharField(choices=[('OW', 'OWNER'), ('SF', 'STAFF'), ('TE', 'TEACHER'), ('ST', 'STUDENT'), ('PT', 'PARENT')], default='SF', max_length=2)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
            options={
                'verbose_name': 'SchoolMember',
                'verbose_name_plural': 'SchoolMembers',
                'db_table': 'SchoolMembers',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OW', 'OWNER'), ('SF', 'STAFF'), ('TE', 'TEACHER'), ('ST', 'STUDENT'), ('PT', 'PARENT')], default='SF', max_length=2)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('WR', 'WARNING'), ('IM', 'IMPORTANT'), ('EV', 'EVENT')], default='IM', max_length=2)),
                ('read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='FCMDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staffs',
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.classe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'db_table': 'Student',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
                ('student', models.ManyToManyField(blank=True, default=[], related_name='parents', to='school_managment.student')),
            ],
            options={
                'verbose_name': 'Parent',
                'verbose_name_plural': 'Parents',
                'db_table': 'Parent',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=255)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.student')),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'Grade',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'db_table': 'Subject',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('exam_name', models.CharField(max_length=200)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('class_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.classe')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
                ('subject_association', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.subject')),
            ],
            options={
                'verbose_name': 'Exam',
                'verbose_name_plural': 'Exams',
                'db_table': 'Exam',
            },
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_taught', to='school_managment.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.IntegerField()),
                ('specialization', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('joining_date', models.DateField(auto_now_add=True)),
                ('teaching_classes', models.ManyToManyField(related_name='teachers', to='school_managment.classe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schoolmembers')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
                'db_table': 'Teacher',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('exam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.exam')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
                'db_table': 'Result',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.classschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
                ('student', models.ManyToManyField(related_name='student', to='school_managment.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'Attendance',
            },
        ),
    ]
