# Generated by Django 5.0.1 on 2024-10-03 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher')),
                ('assigned_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.classroom')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.subject')),
            ],
        ),
    ]
