# Generated by Django 5.0.1 on 2024-03-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classe',
            unique_together=set(),
        ),
    ]
