# Generated by Django 5.0.1 on 2024-02-20 16:44

import school_managment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0002_remove_teacher_contact_number_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='schoolmembers',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=school_managment.models.upload_to),
        ),
    ]
