# Generated by Django 5.0.1 on 2024-10-03 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0002_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='assigned_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.classe'),
        ),
    ]
