# Generated by Django 5.0.1 on 2024-02-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0003_remove_person_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school',)},
        ),
    ]
