# Generated by Django 5.0.1 on 2024-10-06 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0003_alter_homework_assigned_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.subject'),
        ),
    ]
