# Generated by Django 5.0.1 on 2024-11-08 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0004_alter_homework_assigned_by_alter_homework_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='classes_taught',
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(help_text='Enter time in HH:mm format'),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(help_text='Enter time in HH:mm format'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='classes_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms_taught', to='school_managment.classe'),
        ),
    ]
