# Generated by Django 5.0.1 on 2024-02-20 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0004_alter_class_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'class_id')},
        ),
    ]
