# Generated by Django 5.0.1 on 2024-08-23 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0005_alter_person_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='assigned_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.teacher'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='student',
            field=models.ManyToManyField(blank=True, default=[], related_name='parents', to='school_managment.student'),
        ),
    ]
