# Generated by Django 5.0.1 on 2025-01-06 09:32

import school_managment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0006_alter_teacher_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to=school_managment.models.upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='person',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolmembers',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
