# Generated by Django 5.0.1 on 2024-03-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0006_alter_attendance_date_alter_attendance_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='subjects_taught',
        ),
        migrations.AddField(
            model_name='classroom',
            name='subjects_taught',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms_taught', to='school_managment.subject'),
        ),
    ]
