# Generated by Django 5.0.1 on 2025-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0008_expense_financialreport_alter_pubmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'verbose_name': 'Class Schedule', 'verbose_name_plural': 'Class Schedules'},
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('day', 'start_time', 'end_time', 'class_room'), name='unique_schedule_per_room_per_day_per_time'),
        ),
    ]
