# Generated by Django 5.0.1 on 2024-03-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0008_classroom_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.schooldatamodel'),
        ),
    ]
