# Generated by Django 5.0.1 on 2025-01-14 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0009_alter_classschedule_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='fee_structure',
        ),
        migrations.AddField(
            model_name='student',
            name='monthly_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_payment', to='school_managment.monthlypayment'),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_payments', to='school_managment.student'),
        ),
    ]
