# Generated by Django 5.0.1 on 2025-01-14 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0010_remove_student_fee_structure_student_monthly_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlypayment',
            options={'ordering': ['payment_date']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='monthly_payment',
        ),
    ]
