# Generated by Django 5.0.1 on 2025-01-14 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0011_alter_monthlypayment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlypayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_managment.student'),
        ),
    ]
