# Generated by Django 5.0.1 on 2025-01-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0012_alter_monthlypayment_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='activity_fee',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='other_fee',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transportation_fee',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=2, max_digits=50),
        ),
    ]
