# Generated by Django 5.0.1 on 2025-01-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0013_alter_feestructure_activity_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='activity_fee',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='other_fee',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='total_fee',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='transportation_fee',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='tuition_fee',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='balance',
            field=models.DecimalField(decimal_places=4, editable=False, max_digits=50),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='total_expenses',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='total_income',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=50),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='monthlypayment',
            name='total_amount_due',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=50),
        ),
    ]
