# Generated by Django 5.0.1 on 2025-01-15 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0014_alter_expense_amount_alter_feestructure_activity_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='classe_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.classe', unique=True),
        ),
    ]
