# Generated by Django 5.0.1 on 2025-01-15 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_managment', '0015_alter_feestructure_classe_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feestructure',
            name='classe_fee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school_managment.classe'),
        ),
    ]
